# Generated by Django 5.0.3 on 2024-05-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetable',
            name='accumulated_time',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='duration',
        ),
        migrations.AddField(
            model_name='timetable',
            name='total_time',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
